# Maven



# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java



pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/settings.xml'
    TargetFolder: '/usr/share/apache-maven-3.8.1/.m2'
    OverWrite: true
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonar-test'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=helloworld_helloworld

    

- task: CmdLine@2
  inputs:
    script: |
      ls
      pwd
      echo $(system.defaultworkingdirectory)
   #   mvn help:effective-settings


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'artifacts'